name: Reusable Deploy
on: workflow_call
jobs:
    deploy:
        runs-on: ubunut-latest
        steps:
            - name: Output information
              run: echo "Deploying & Uploading..."

              